@startuml
[*] --> Initialize:List of Players
scale 600 width
state Initialize {
  Initialize: Create Deck
  Initialize -down-> Deal
}

state Deal {
  [*] --> DealToAllPlayers
  DealToAllPlayers --> DealToDealer

  Deal -down-> Insurance: Dealer Face Up Card Ace
  Deal -down-> Moves: Dealer Not Showing Ace
}

state Insurance{
  Insurance -down->Moves
}

state Moves{
[*] --> AskPlayerMove

}

@enduml